// Auto-generated by: supabase gen types typescript --local
// Do not edit manually. Run `pnpm db:generate` to regenerate.
//
// Stub file — will be replaced after Supabase migrations are applied (Plan 03).

export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
