root = "."
tmp_dir = "/tmp/air"

[build]
  cmd = "go build -o /tmp/air/worker ./cmd/worker"
  bin = "/tmp/air/worker"
  delay = 1000
  exclude_dir = ["vendor", "testdata", "bin"]
  include_ext = ["go", "mod"]
  kill_delay = "0s"

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
